framework:
    secret: '%env(APP_SECRET)%'
    default_locale: '%env(APP_LOCALE)%'
    csrf_protection: false
    http_method_override: true

    session:
        handler_id: ~

    php_errors:
        log: true

    templating:
        engines:
        - twig