lexik_jwt_authentication:
    secret_key:  '%kernel.project_dir%/resources/jwt/private.pem' # required for token creation
    public_key: '%kernel.project_dir%/resources/jwt/public.pem'  # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:        3600