imports:
    - { resource: config.yaml }
    - { resource: services/mail_services.yaml }
    - { resource: services/security_services.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tools\Clock\SystemClock: ~
    App\Tools\Clock\ClockInterface: '@App\Tools\Clock\SystemClock'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\HttpResponseBuilder\:
        resource: '../src//HttpResponseBuilder/'

    App\Domain\DataInteractor\:
        resource: '../src/Domain/DataInteractor/'

    App\Event\Listener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\Event\Listener\Dev\ApiRequestEventListener:
        arguments:
            $defaultUserId: '%default_user_id%'
            $wrapApiResponse: '%wrap_api_response%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: addTokenToRequest, priority: 999 }
            - { name: kernel.event_listener, event: kernel.response, method: convertResponseToHtml }