imports:
    - { resource: services/security_services.yaml }

parameters:
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Tools\Clock\SystemClock: ~
    App\Tools\Clock\ClockInterface: '@App\Tools\Clock\SystemClock'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\HttpResponseBuilder\:
        resource: '../src//HttpResponseBuilder/*'

    App\Domain\DataInteractor\:
        resource: '../src/Domain/DataInteractor/*'
